import type { Metadata } from "next";
import { Anton, Work_Sans } from "next/font/google"
import "./globals.css";
import { Providers } from "@/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const work_sans = Work_Sans({ weight: ['200', "300", "400", "700"], subsets: ["latin"], style: ["normal", "italic"], display: "swap", variable: "--font-worksans" });
const anton = Anton({ weight: "400", subsets: ["latin"], display: "swap", variable: "--font-anton" });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${work_sans.variable} ${anton.variable}`}>
        <div className="w-screen h-screen overflow-hidden bg-navy">
          <Providers>
            {children}
          </Providers>
        </div>
      </body>
    </html>
  );
}
